### ISSUE TITLE
Would this work with Flutter?

### ISSUE THREAD

**Issue by Catsvilles** [maks/dart_synth#1]
Hi @maks, saw your issue at petersalomonsen's repo. Very curious, if this potentially can work in Flutter projects on Android and IOS? From my research, at the moment Flutter doesn't support WASM. But there is a way to wrap C and C++ libraries.

**Comment by maks** [comment]
Potentially it should work with Flutter, I'm at least planning to try it with Flutter in the near future.

Though the goal of this specific project is just to investigate integrating the (very) new wasm Dart package to run assemblyscript from Peter's project along with audio playback on Linux (which I already have working). Because this is intended for a project which will be running "headless" ona RPI using a specific midi controller for all user interactions, I'm focusing on just pure Dart at the moment.

On the general topic of WASM in iOS, because the Dart package is using wasmer, while it seems *technically* [possible to use wasmer on iOS](http://www.alwaysrightinstitute.com/swifty-wasmer/), I am unsure if this will run afoul of Apple's AppStore policy restrictions on JITs in iOS apps.

**Comment by Catsvilles** [comment]
https://github.com/dart-lang/wasm/issues/40#issuecomment-909514442

Maybe this potentially can help running it easily in Flutter
